name: Alexa Skill lambda CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
#    - run: npm test

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: alexa_lambda
        path: distro.zip
        retention-days: 1
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download zip file
        uses: actions/download-artifact@v2
        with:
          name: alexa_lambda

      - name: Lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: alexa_lambda
          zip_file: distro.zip
          memory_size: 128
          timeout: 10
          handler: index.handler
          role: ${{ secrets.AWS_ARN }}
          runtime: nodejs12.x
